name: Run Unit Tests

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest

        services:
            postgres:
              image: postgres:17.3-alpine
              env:
                POSTGRES_USER: root
                POSTGRES_PASSWORD: root
                POSTGRES_DB: nanachat
              options: >-
                --health-cmd pg_isready
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5
              ports:
                - 5432:5432
        
        steps:

        - name: Setup Go 1.x
          uses: actions/setup-go@v5
          with:
            go-version: ^1.24
            cache: true
          id: go

        - name: Check out code into the Go module directory
          uses: actions/checkout@v4

        - name: Install golang-migrate cli
          run: |
            curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.2/migrate.linux-amd64.tar.gz | tar xvz
            sudo mv migrate /usr/bin/migrate
            which migrate
        
        - name: Run migrations
          run: make migrateup

        - name: Test
          run: make test